### ISSUE TITLE
Rename `lmdb-delete` and add support for deleting keys?

### ISSUE THREAD

**Issue by caolan** [iraikov/chicken-lmdb#5]
The `lmdb-delete` procedure deletes the files associated with a database. I'd like to suggest we use `lmdb-delete!` to delete **keys** from a database instead, as this would be in line with the srfi-69 naming style used elsewhere. The original `lmdb-delete` might be renamed to `lmdb-destroy` or `lmdb-delete-database` or similar.

If you agree with this change I'm happy to make a start on it. We currently don't have a way to delete keys.

**Comment by iraikov** [comment]
Yes, this is sensible, I remember seeing the discrepancy with srfi-69 when I originally ported to the code, but never bothered to correct it as I am generally using lmdb only for persistent storage. Let's rename the original lmdb-delete to lmdb-delete-database for now.
