### ISSUE TITLE
Separate encryption layer

### ISSUE THREAD

**Issue by caolan** [iraikov/chicken-lmdb#8]
For my own project, I don't need the encryption of keys/values and would like to avoid the rabbit egg dependency. How do you feel about me splitting that out into a wrapper module, something like lmdb-rabbit?

My vague plan would be to keep most the code the same and use a functor module to make the key/value encoding a parameter (which defaults to identity).

**Comment by iraikov** [comment]
Ok, let's give it a try. I don't use the encryption myself, and I don't have a clear idea what a modular design would look like, but we can try iterating through some prototype designs.

**Comment by caolan** [comment]
Oh, do we know if anyone uses it? Perhaps we can just remove it?

**Comment by iraikov** [comment]
Well, I think it's elegant, and the rabbit egg is trivial to install, so I would like to keep the encryption. Perhaps one of us or future users would find it useful to store some kind of sensitive information.
